### ISSUE TITLE
createPauliHamil does not initialize memory in unit tests

### ISSUE THREAD

**Issue by mattchan-tencent** [HQSquantumsimulations/PyQuEST-cffi#31] opened 2021-01-28 22:56 UTC
In `cheat.test_measurement.test_calc_Expec_Pauli_Hamil` and in `test_ops.test_applied_functions`, the `term_coeffs` property is not initialized because `cheat.initPauliHamil` is not called. I think this leads to segfaults and undefined behavior I've been getting in the unit tests.

The requirement to initialize is mentioned here: https://quest-kit.github.io/QuEST/group__type.html#ga35b28710877c462927366fa602e591cb

**Comment by nfwvogt** [comment] 2021-02-01 16:48
Thanks for the report, we are in the process of setting up more automated unit testing here on github, and interestingly it seems the issue is only visible on the mac os runners. We will start working on a fix.

**Comment by mattchan-tencent** [comment] 2021-02-01 22:28
Ah yes. I didn't have that issue on Linux. I'm not sure if it's because of different illegal memory access checks or some GCC/Clang differences. 

Thanks for letting me know about the CI stuff. Looking forward to it!

**Comment by nfwvogt** [comment] 2021-02-03 14:14
So the issue of the un-initialised Pauli Hamiltonian has been addressed and unittests pass on macos with python 3.9.  
Curiously on macos in combination with python 3.7 and python 3.8 some unittests for the operations still fail (#36 ).  
It will take a little time until we can check what is going on there. In the meantime if you have access to a python 3.9 install and need the Pauli Hamiltonian initialisation fixed, the develop branch should be working now.

**Comment by nfwvogt** [comment] 2021-02-19 07:49
Fixed by #41

**Closed by nfwvogt** 2021-02-19 07:49 UTC
